import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { mealPlanAPI } from '../services/api';
import { useAuth } from '../contexts/AuthContext';
import firebaseService from '../services/firebaseService';
import './MealPlanner.css';

function MealPlanner() {
  const { currentUser, userProfile } = useAuth();
  const [preferences, setPreferences] = useState({
    duration: 7,
    mealsPerDay: 3,
    cuisinePreferences: [],
  });

  const [mealPlan, setMealPlan] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [showSaveModal, setShowSaveModal] = useState(false);
  const [saveSuccess, setSaveSuccess] = useState('');

  const handleChange = (e) => {
    const { name, value } = e.target;
    setPreferences(prev => ({ ...prev, [name]: parseInt(value) || value }));
  };

  const handleCuisineChange = (e) => {
    const value = e.target.value;
    if (value && !preferences.cuisinePreferences.includes(value)) {
      setPreferences(prev => ({
        ...prev,
        cuisinePreferences: [...prev.cuisinePreferences, value]
      }));
    }
  };

  const removeCuisine = (cuisine) => {
    setPreferences(prev => ({
      ...prev,
      cuisinePreferences: prev.cuisinePreferences.filter(c => c !== cuisine)
    }));
  };

  const generateMealPlan = async () => {
    if (!userProfile) {
      setError('Please create your health profile first');
      return;
    }

    setLoading(true);
    setError('');
    
    try {
      const response = await mealPlanAPI.generate(userProfile, preferences);
      setMealPlan(response.data.data);
      setShowSaveModal(true); // Show save modal after successful generation
    } catch (err) {
      setError('Failed to generate meal plan. Please try again.');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const saveMealPlanToProfile = async () => {
    try {
      // Create new meal plan entry
      const newPlan = {
        id: Date.now(),
        mealPlan: mealPlan.mealPlan,
        preferences: preferences,
        generatedAt: mealPlan.generatedAt,
        savedAt: new Date().toISOString(),
        userProfile: {
          age: userProfile.age,
          gender: userProfile.gender,
          activityLevel: userProfile.activityLevel
        }
      };
      
      // Save to Firebase if user is logged in
      if (currentUser) {
        await firebaseService.saveMealPlan(currentUser.uid, newPlan);
      } else {
        // Fall back to localStorage if not logged in
        const savedPlans = JSON.parse(localStorage.getItem('savedMealPlans') || '[]');
        savedPlans.unshift(newPlan);
        if (savedPlans.length > 10) {
          savedPlans.pop();
        }
        localStorage.setItem('savedMealPlans', JSON.stringify(savedPlans));
      }
      
      setShowSaveModal(false);
      setSaveSuccess(currentUser ? '✅ Meal plan saved to your profile!' : '✅ Meal plan saved locally!');
      
      // Clear success message after 3 seconds
      setTimeout(() => setSaveSuccess(''), 3000);
    } catch (err) {
      console.error('Failed to save meal plan:', err);
      setError('Failed to save meal plan. Please try again.');
    }
  };

  const skipSaving = () => {
    setShowSaveModal(false);
  };

  return (
    <div className="container">
      <div className="card">
        <div className="card-header">
          <h1 className="card-title">AI Meal Planner</h1>
          <p className="card-subtitle">Get a personalized meal plan generated by AI</p>
        </div>

        {error && <div className="error">{error}</div>}
        {saveSuccess && <div className="success">{saveSuccess}</div>}

        <div className="preferences-section">
          <div className="form-row">
            <div className="form-group">
              <label className="form-label">Duration (days)</label>
              <select
                name="duration"
                className="form-select"
                value={preferences.duration}
                onChange={handleChange}
              >
                <option value={1}>1 Day</option>
                <option value={3}>3 Days</option>
                <option value={7}>7 Days (1 Week)</option>
                <option value={14}>14 Days (2 Weeks)</option>
                <option value={30}>30 Days (1 Month)</option>
              </select>
            </div>

            <div className="form-group">
              <label className="form-label">Meals Per Day</label>
              <select
                name="mealsPerDay"
                className="form-select"
                value={preferences.mealsPerDay}
                onChange={handleChange}
              >
                <option value={2}>2 Meals</option>
                <option value={3}>3 Meals</option>
                <option value={4}>4 Meals</option>
                <option value={5}>5 Meals + Snacks</option>
                <option value={6}>6 Small Meals</option>
              </select>
            </div>
          </div>

          <div className="form-group">
            <label className="form-label">Cuisine Preferences (Optional)</label>
            <select
              className="form-select"
              onChange={handleCuisineChange}
              value=""
            >
              <option value="">Select cuisines...</option>
              <option value="Indian">Indian</option>
              <option value="Mediterranean">Mediterranean</option>
              <option value="Asian">Asian</option>
              <option value="Mexican">Mexican</option>
              <option value="Italian">Italian</option>
              <option value="American">American</option>
              <option value="Middle Eastern">Middle Eastern</option>
              <option value="Continental">Continental</option>
            </select>
            <div className="tags-container">
              {preferences.cuisinePreferences.map(cuisine => (
                <span key={cuisine} className="tag">
                  {cuisine} <button type="button" onClick={() => removeCuisine(cuisine)}>×</button>
                </span>
              ))}
            </div>
          </div>

          <button 
            className="btn btn-primary btn-large"
            onClick={generateMealPlan}
            disabled={loading}
          >
            {loading ? '🔄 Generating Your Meal Plan...' : '✨ Generate Meal Plan'}
          </button>
        </div>
      </div>

      {loading && (
        <div className="card loading-card">
          <div className="loading-animation">
            <div className="spinner"></div>
            <p>AI is crafting your personalized meal plan...</p>
            <p className="loading-subtext">This may take 10-20 seconds</p>
          </div>
        </div>
      )}

      {mealPlan && !loading && (
        <div className="card meal-plan-result">
          <div className="result-header">
            <h2>Your Personalized Meal Plan</h2>
            <p className="plan-info">
              {preferences.duration} days • {preferences.mealsPerDay} meals per day
            </p>
            <p className="generated-time">
              Generated on {new Date(mealPlan.generatedAt).toLocaleString()}
            </p>
          </div>

          <div className="meal-plan-content markdown-content">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {mealPlan.mealPlan}
            </ReactMarkdown>
          </div>

          <div className="action-buttons">
            <button className="btn btn-primary" onClick={() => window.print()}>
              🖨️ Print Meal Plan
            </button>
            <button 
              className="btn btn-secondary"
              onClick={() => {
                navigator.clipboard.writeText(mealPlan.mealPlan);
                alert('Meal plan copied to clipboard!');
              }}
            >
              📋 Copy to Clipboard
            </button>
          </div>
        </div>
      )}

      {/* Save to Profile Modal */}
      {showSaveModal && (
        <div className="modal-overlay" onClick={skipSaving}>
          <div className="save-modal" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h3>💾 Save Meal Plan?</h3>
            </div>
            <div className="modal-body">
              <p>Would you like to save this meal plan to your Health Profile?</p>
              <p className="modal-subtext">
                You can view all your saved meal plans in the Health Profile section.
              </p>
            </div>
            <div className="modal-actions">
              <button className="btn btn-primary" onClick={saveMealPlanToProfile}>
                ✅ Yes, Save It
              </button>
              <button className="btn btn-secondary" onClick={skipSaving}>
                ❌ No, Thanks
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default MealPlanner;
